name: Deploy LLM Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pulumi pulumi-digitalocean pulumi-command uv

      - name: Pulumi Deploy
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

        run: |
          set -e

          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Exporting private key..."
          export PRIVATE_KEY="$(cat ~/.ssh/id_rsa)"

          echo "Selecting stack..."
          pulumi stack select dev || pulumi stack init dev

          echo "Setting configs..."
          pulumi config set ssh_fingerprint "${{ secrets.SSH_FINGERPRINT }}"
          pulumi config set --secret hf_token "${{ secrets.HF_TOKEN }}"
          pulumi config set model_repo "repo/name"

          echo "Deploying..."
          pulumi up --yes